init:
    $ circlewipe = ImageDissolve("by_Kia/circlewipe-cw.jpg", 1.0, 8)
    $ ccirclewipe = ImageDissolve("by_Kia/circlewipe-ccw.jpg", 1.0, 8)
    $ bites = ImageDissolve("by_Kia/bites.jpg", 1.0, 8)
    $ bowtie = ImageDissolve("by_Kia/bowtie.png", 1.0, 8)
    $ cmet = ImageDissolve("by_Kia/cmet.jpg", 1.0, 8)
    $ cwside = ImageDissolve("by_Kia/cw-side.jpg", 1.0, 8)
    $ cwtop = ImageDissolve("by_Kia/cw-top.jpg", 1.0, 8)
    $ dots = ImageDissolve("by_Kia/dots.png", 1.0, 8)
    $ edges = ImageDissolve("by_Kia/edges.png", 1.0, 8)
    $ flips = ImageDissolve("by_Kia/flips.png", 1.0, 8)
    $ fur = ImageDissolve("by_Kia/fur.jpg", 1.0, 8)
    $ goslow = ImageDissolve("by_Kia/goslow.png", 5.0, 8)
    $ letter = ImageDissolve("by_Kia/letter.png", 1.0, 8)
    $ maze = ImageDissolve("by_Kia/maze.png", 1.0, 8)
    $ radio = ImageDissolve("by_Kia/radio.jpg", 1.0, 8)
    $ snake = ImageDissolve("by_Kia/snake.png", 1.0, 8)
    $ snake2 = ImageDissolve("by_Kia/snake2.png", 1.0, 8)
    $ snakes = ImageDissolve("by_Kia/snakes.png", 1.0, 8)
    $ sunshine = ImageDissolve("by_Kia/sunshine.jpg", 1.0, 8)
    $ glasswool = ImageDissolve("by_Kia/glasswool.jpg", 1.0, 8)
    $ wet = ImageDissolve("by_Kia/wet.jpg", 1.0, 8)

    $ curtains = ImageDissolve("by_Kia/curtains.png", 1.0, 8)

    $ snow1 = ImageDissolve("by_Kia/snow1.png", 1.0, 8)
    $ rain1 = ImageDissolve("by_Kia/rain1.jpg", 1.0, 8)
    $ rain2 = ImageDissolve("by_Kia/rain2.jpg", 1.0, 8)

    $ puzz = ImageDissolve("by_Kia/puzz.png", 1.0, 8)

    $ shatter = ImageDissolve("by_Kia/shatter.png", 1.0, 8)
    $ shot = ImageDissolve("by_Kia/shot.png", 1.0, 8)


# unnamed
    $ w1 = ImageDissolve("by_Kia/1.jpg", 1.0, 8)
    $ w2 = ImageDissolve("by_Kia/2.png", 1.0, 8)
    $ w3 = ImageDissolve("by_Kia/3.jpg", 1.0, 8)
    $ w4 = ImageDissolve("by_Kia/4.jpg", 1.0, 8)
    $ w5 = ImageDissolve("by_Kia/5.jpg", 1.0, 8)
    $ w6 = ImageDissolve("by_Kia/6.jpg", 1.0, 8)
    $ w7 = ImageDissolve("by_Kia/7.png", 1.0, 8)
    $ w8 = ImageDissolve("by_Kia/8.jpg", 1.0, 8)
    $ w9 = ImageDissolve("by_Kia/9.jpg", 1.0, 8)
    $ w10 = ImageDissolve("by_Kia/10.jpg", 1.0, 8)
    $ w11 = ImageDissolve("by_Kia/11.jpg", 1.0, 8)
    $ w12 = ImageDissolve("by_Kia/12.jpg", 1.0, 8)
    $ w13 = ImageDissolve("by_Kia/13.jpg", 1.0, 8)
    $ w14 = ImageDissolve("by_Kia/14.png", 1.0, 8)
    $ w15 = ImageDissolve("by_Kia/15.png", 1.0, 8)
    $ w16 = ImageDissolve("by_Kia/16.png", 1.0, 8)
    $ w17 = ImageDissolve("by_Kia/17.png", 1.0, 8)
    $ w18 = ImageDissolve("by_Kia/18.png", 1.0, 8)
    $ w19 = ImageDissolve("by_Kia/19.jpg", 1.0, 8)
    $ w20 = ImageDissolve("by_Kia/20.jpg", 1.0, 8)
    $ w21 = ImageDissolve("by_Kia/21.jpg", 1.0, 8)
    $ w22 = ImageDissolve("by_Kia/22.png", 1.0, 8)
    $ w23 = ImageDissolve("by_Kia/23.png", 1.0, 8)
    $ w24 = ImageDissolve("by_Kia/24.png", 1.0, 8)
    $ w25 = ImageDissolve("by_Kia/25.png", 1.0, 8)
    $ w26 = ImageDissolve("by_Kia/26.png", 1.0, 8)
    $ w27 = ImageDissolve("by_Kia/27.png", 1.0, 8)
    $ w28 = ImageDissolve("by_Kia/28.png", 1.0, 8)

    $ w29 = ImageDissolve("by_Kia/29.png", 1.0, 8)
    $ w30 = ImageDissolve("by_Kia/30.png", 1.0, 8)
    $ w31 = ImageDissolve("by_Kia/31.png", 1.0, 8)
    $ w32 = ImageDissolve("by_Kia/32.png", 1.0, 8)
    $ w33 = ImageDissolve("by_Kia/33.png", 1.0, 8)

    $ w34 = ImageDissolve("by_Kia/34.png", 1.0, 8)
    $ w35 = ImageDissolve("by_Kia/35.jpg", 1.0, 8)
    $ w36 = ImageDissolve("by_Kia/36.jpg", 1.0, 8)
    $ w37 = ImageDissolve("by_Kia/37.png", 1.0, 8)
